export const OPEN_LANG_CURRENCY_POPUP = 'OPEN_LANG_CURRENCY_POPUP'
export const CLOSE_LANG_CURRENCY_POPUP = 'CLOSE_LANG_CURRENCY_POPUP'
export const TOGGLE_LANG_CURRENCY_POPUP = 'TOGGLE_LANG_CURRENCY_POPUP'

export const OPEN_ACCOUNT_MENU_POPUP = 'OPEN_ACCOUNT_MENU_POPUP'
export const CLOSE_ACCOUNT_MENU_POPUP = 'CLOSE_ACCOUNT_MENU_POPUP'
export const TOGGLE_ACCOUNT_MENU_POPUP = 'TOGGLE_ACCOUNT_MENU_POPUP'

export const OPEN_ACCOUNT_CLUB_MENU_POPUP = 'OPEN_ACCOUNT_CLUB_MENU_POPUP'
export const CLOSE_ACCOUNT_CLUB_MENU_POPUP = 'CLOSE_ACCOUNT_CLUB_MENU_POPUP'
export const TOGGLE_ACCOUNT_CLUB_MENU_POPUP = 'TOGGLE_ACCOUNT_CLUB_MENU_POPUP'

export const OPEN_CONTACTS_POPUP = 'OPEN_CONTACTS_POPUP'
export const CLOSE_CONTACTS_POPUP = 'CLOSE_CONTACTS_POPUP'
export const TOGGLE_CONTACTS_POPUP = 'TOGGLE_CONTACTS_POPUP'

export const CLOSE_ALL_POPUPS = 'CLOSE_ALL_POPUPS'
